<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EM.Domain\ExpenseManagement.Domain\ExpenseManagement.Domain.csproj" />
    <ProjectReference Include="..\ExpenseManagement.Application.Contract\ExpenseManagement.Application.Contract.csproj" />
  </ItemGroup>

</Project>
